### ISSUE TITLE
ignore `rel="external"`

### ISSUE THREAD

**Issue by layflags** [HenrikJoreteg/internal-nav-helper#3]
Hi Henrik, 

what do you think about adding `rel="external"` to the ignore list? 

I have the situation where I need to link to an API endpoint (same host/port like my app) which then redirects the user to an external URL for authentication. This is currently not possible and `rel="external"` would be an appropriate standard for doing that. 

MDN says: 
> Indicates that the hyperlink leads to a resource outside the site of the current page; that is, following the link will make the user leave the site.

https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types

Does that make sense to you?

**Comment by HenrikJoreteg** [comment]
makes good sense to me, published as `3.1.0`. Thanks!
